console.log("Текст из script.js!");
let num = 123;
console.log(num);
let a = 5;
a = 7;
console.log(a);
let b = 1 + 2 + 3;
console.log(b);
//семинар;
/* многострочный комментарий*/
let c = 10;
let d = 2;
let sum = c + d;
let difference = c - d;
let products = c * d;
let deleniye = c / d;
console.log(c, d, sum, difference, products, deleniye);
let result = c + d + sum + difference + products + deleniye;
console.log(result);
let e = 1.5;
let f = 0.75;
let summa = e + f;
console.log(summa);
let g = -20;
console.log(-g);
